# Generated by Django 6.0.4 on 2026-05-04 20:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MatchData',
            fields=[
                ('id_match', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=100)),
                ('surface', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'match_data',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id_player', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'player',
            },
        ),
        migrations.CreateModel(
            name='MatchScore',
            fields=[
                ('id_match_score', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('duration', models.DurationField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_scores', to='matches.matchdata')),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_wins', to='matches.player')),
            ],
            options={
                'db_table': 'match_score',
                'unique_together': {('id_partido', 'winner_id')},
            },
        ),
        migrations.CreateModel(
            name='MatchSet',
            fields=[
                ('id_set', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_player_1', models.IntegerField()),
                ('score_player_2', models.IntegerField()),
                ('duration', models.DurationField()),
                ('id_match_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_sets', to='matches.matchscore')),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_wins', to='matches.player')),
            ],
            options={
                'db_table': 'match_set',
            },
        ),
        migrations.AddField(
            model_name='matchdata',
            name='player_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1_matches', to='matches.player'),
        ),
        migrations.AddField(
            model_name='matchdata',
            name='player_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2_matches', to='matches.player'),
        ),
        migrations.CreateModel(
            name='MatchPoint',
            fields=[
                ('id_point', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score_player_1', models.IntegerField()),
                ('score_player_2', models.IntegerField()),
                ('duration', models.DurationField()),
                ('break_point_chance', models.BooleanField()),
                ('break_point', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_points', to='matches.matchscore')),
                ('id_player_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_1_points', to='matches.player')),
                ('id_player_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_2_points', to='matches.player')),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_wins', to='matches.player')),
            ],
            options={
                'db_table': 'match_point',
                'unique_together': {('id_game', 'id_player_1', 'id_player_2', 'winner_id')},
            },
        ),
        migrations.CreateModel(
            name='MatchGame',
            fields=[
                ('id_game', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('p1_game_final_score', models.IntegerField()),
                ('p2_game_final_score', models.IntegerField()),
                ('duration', models.DurationField()),
                ('is_break', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_games', to='matches.matchset')),
                ('winner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_wins', to='matches.player')),
            ],
            options={
                'db_table': 'match_game',
                'unique_together': {('id_set', 'winner_id')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='matchdata',
            unique_together={('player_1', 'player_2')},
        ),
    ]
