# Generated by Django 5.2.13 on 2026-04-28 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='tipoUsuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nivelUsuario',
            field=models.CharField(choices=[('Entrenador', 'Entrenador'), ('Amateur', 'Amateur'), ('Semi-Pro', 'Semipro'), ('Profesional', 'Pro')], default='Amateur', max_length=20),
        ),
    ]
